spring.application.name=apnaprojectname-9
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_jdbcd
spring.datasource.username=root
spring.datasotce.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
